### PR TITLE
Add support for partial validate method

### LINKED ISSUE #5: Feature request: Generate partial validation method
It would be appropriate to generate partial methods for the validation of the value.

Code:
```cs
[WrapperValueObject(typeof(decimal))] readonly partial struct Money { }
```

Generates eg.:
```cs
partial struct Money 
{
    private decimal _value;

    
    public Money(decimal value)
    {
         Validate(value);
         _value = value;
    } 

   partial void Validate(decimal value);
   // ...
}
```

And if the consumer of api will want to implement value check/validation, then implements method _Validate_.

```cs
[WrapperValueObject(typeof(decimal))] 
readonly partial struct Money 
{
    partial void Validate(decimal value)
    {
         if(value<0.0) throw new ArgumentException("Money value can not by less than zero.");
    }
 }
```

Use cases:
 - Databse IDs (must by more than zero),
 - String keys in specific format (for nosql databases),
 - Percent (0-100%),
 - Special units (PH, °C,...)

### PR DESCRIPTION
**Pull request by viceroypenguin**
Fixes #5 

NB#1: Validate  method must be `static partial void Validate(<type> value);`.
NB#2: I didn't update any documentation.

### CODE REVIEW

**Comment by martinothamar** [comment]
Thanks! One case that isn't covered here is compound types, where the generated inner type is a value tuple. I think it would be better for the generated partial Validate method to have the argument not be a value tuple in that case, rather 1 arg per field in the type similar to the constructor that is generated . What do you think?

**Comment by viceroypenguin** [comment]
I thought about that, but I didn't want to go through the effort... :)  I'll do an update soon.

**Comment by viceroypenguin** [comment]
Also, doing it as in arg per field makes the base case more complicated (see L247 - currently simply `Validate(other)`)

**Review by martinothamar — APPROVED** [review]
great 🥇  thank you!

**Pull request merged**
